version = 0.1
[default.deploy.parameters]
stack_name = "microsocial-backend-dev"
resolve_s3 = true
s3_prefix = "microsocial-backend-dev"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
